### ISSUE TITLE
RecruitPlotEasy crashes at Database creation step

### ISSUE THREAD

**Issue by michaelwoodworth** [KGerhardt/RecruitPlotEasy#3]
Hi, thanks for creating/maintaining this shiny tool. I am trying to create some recruitment plots but it keeps crashing at the database creation step and giving me the Warning and text below. Any ideas for how to resolve this?

thanks!

Mike

```r
> library(RecruitPlotEasy)
> RecruitPlotEasy()
Initiating recruitment plot environment. Please wait a moment. Recruitment plots ready.
Loading required package: shiny

Listening on http://127.0.0.1:7524
Warning: Error in py_get_attr_impl: AttributeError: module 'RecruitPlotEasy' has no attribute 'reads_database'
  [No stack trace available]

Thank you for using Recruitment Plots!
Any databases you created or plots you made are stored in: /Users/NewNasty/OneDrive - Emory University/Box/MEP/Projects/Culture Bias/Analyses/Data/Metagenomes/MIGS/recruitment_plots
```

**Comment by KGerhardt** [comment]
The code at this point in time was still under revision. It's likely that there was a version discrepancy between the R and python code.

I apologize for missing this issue - if you would be willing to try it again, it should now work for you.

**Comment by Kimmmma** [comment]
I am still getting that same issue with the updated version. The screen goes grey after creating a database and adding genomes to it-it will not allow me to proceed. Suggestions?
